version: '3.3'

services:

  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "7000:8000"
    volumes:
      - "./.docker/dynamodb/volume:/home/dynamodblocal/data"
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath /home/dynamodblocal/data"

  aws-cli-local:
    container_name: aws-cli-local
    build:
      context: ./scripts/dynamodb_docker/
      dockerfile: Dockerfile_aws_cli
    command: "./awscli_script.sh"
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local

  dynamodb-local-admin-gui:
    container_name: dynamodb-local-admin-gui
    image: instructure/dynamo-local-admin
    ports:
      - '7001:8001'
      - '7002:8002'
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
    depends_on:
      - dynamodb-local
    links:
      - dynamodb-local

  spring-app:
    container_name: spring-app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'