package com.example.dynamoDemo.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "ProductCatalog")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder(toBuilder = true)
public class Product {

    @DynamoDBHashKey(attributeName = "Id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "InPublication")
    private Boolean inPublication;

    @DynamoDBAttribute(attributeName = "ISBN")
    private String isbn;

    @DynamoDBAttribute(attributeName = "PageCount")
    private Integer pageCount;

    @DynamoDBAttribute(attributeName = "Price")
    private Integer price;

    @DynamoDBAttribute(attributeName = "Authors")
    private List<String> authors;

    @DynamoDBAttribute(attributeName = "ProductCategory")
    private String productCategory;

    @DynamoDBAttribute(attributeName = "Title")
    private String title;

    @DynamoDBAttribute(attributeName = "Dimensions")
    private String dimensions;

    @DynamoDBAttribute(attributeName = "Brand")
    private String brand;

    @DynamoDBAttribute(attributeName = "Description")
    private String description;

    @DynamoDBAttribute(attributeName = "Color")
    private List<String> color;

    @DynamoDBAttribute(attributeName = "BicycleType")
    private String bicycleType;

}
