server:
  port: 8080

application.support.email: "nizami.islamovs@gmail.com"

spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: springboot-aws-dynamodb

amazon:
  aws:
    accesskey: DUMMYIDEXAMPLE
    region: us-west-2
    secretkey: DUMMYEXAMPLEKEY
  dynamodb:
    endpoint: 'http://dynamodb-local:8000/'


management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
      cors:
        allowed-methods: GET, POST, PUT, DELETE, OPTIONS
        max-age: 3600s
        #        allowed-origins: '*'
        allow-credentials: true


springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method