FROM python:3.7-alpine3.9

WORKDIR /data
COPY ./volume /data

LABEL python-version=3.7

ENV PATH="/root/.local/bin:$PATH"
ENV PYTHONIOENCODING=UTF-8

RUN apk add --no-cache jq
RUN pip install --user awscli

ENV AWS_ACCESS_KEY_ID 'DUMMYIDEXAMPLE'
ENV AWS_SECRET_ACCESS_KEY 'DUMMYEXAMPLEKEY'

RUN ["chmod", "+x", "./awscli_script.sh"]

ENTRYPOINT ["/bin/sh", "-c"]